### ISSUE TITLE
Header collapsed/expanded state

### ISSUE THREAD

**Issue by asg5704** [CaitHawk/portfolio-react#1]
https://github.com/CaitHawk/portfolio-react/blob/0146ebea14c295d33e96a9b45539c6959e269e40/src/pages/Header.js#L41-L44

```javascript
  const [isOpen, setIsOpen] = useState(false) // closed menu by default
  
  <Menu className={`isOpen ? 'opened-menu-class' : 'closed-menu-class'`}>
    <button onClick={() => setIsOpen(!isOpen)}>
  </Menu>
```

**Comment by CaitHawk** [comment]
Thank you! I was planning to write a toggle state hook to use in the header
collapsed and a few accordions. I’m kind of just throwing something
together so I can link it. This portfolio will be super minimalist but I’m
okay with that.
